# Generated by Django 5.1.2 on 2024-11-13 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pitcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pitcher_name', models.CharField(max_length=50)),
                ('pitcher_age', models.PositiveIntegerField()),
                ('pitcher_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('pitcher_position', models.CharField(choices=[('SP', 'Starter'), ('RP', 'Reliever'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('pitcher_height', models.CharField(max_length=4)),
                ('pitcher_weight', models.CharField(max_length=3)),
                ('pitcher_SO', models.PositiveIntegerField(default=0)),
                ('pitcher_hits', models.PositiveIntegerField(default=0)),
                ('pitcher_walks', models.PositiveIntegerField(default=0)),
                ('pitcher_HR', models.PositiveIntegerField(default=0)),
                ('pitcher_IP', models.FloatField(default=0)),
                ('pitcher_runs', models.PositiveIntegerField(default=0)),
                ('pitcher_ER', models.PositiveIntegerField(default=0)),
                ('pitcher_games', models.PositiveIntegerField(default=0)),
                ('pitcher_GS', models.PositiveIntegerField(default=0)),
                ('pitcher_AB', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('player_age', models.PositiveIntegerField()),
                ('player_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('player_position', models.CharField(choices=[('1B', 'Firstbase'), ('2B', 'Secondbase'), ('SS', 'Shortstop'), ('3B', 'Thirdbase'), ('C', 'Catcher'), ('OF', 'Outfield'), ('N/A', 'N/A')], default='N/A', max_length=10)),
                ('player_height', models.CharField(max_length=4)),
                ('player_weight', models.CharField(max_length=3)),
                ('player_games', models.PositiveIntegerField(default=0)),
                ('player_hits', models.PositiveIntegerField(default=0)),
                ('player_AB', models.PositiveIntegerField(default=0)),
                ('player_BB', models.PositiveIntegerField(default=0)),
                ('player_SO', models.PositiveIntegerField(default=0)),
                ('player_Singles', models.PositiveIntegerField(default=0)),
                ('player_Doubles', models.PositiveIntegerField(default=0)),
                ('player_Triples', models.PositiveIntegerField(default=0)),
                ('player_HR', models.PositiveIntegerField(default=0)),
                ('player_Runs', models.PositiveIntegerField(default=0)),
                ('player_RBI', models.PositiveIntegerField(default=0)),
                ('player_SB', models.PositiveIntegerField(default=0)),
                ('player_SAC', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GamePitcherStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SO', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('walks', models.PositiveIntegerField(default=0)),
                ('HR', models.PositiveIntegerField(default=0)),
                ('IP', models.FloatField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('ER', models.PositiveIntegerField(default=0)),
                ('games', models.PositiveIntegerField(default=0)),
                ('GS', models.PositiveIntegerField(default=0)),
                ('AB', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.game')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.pitcher')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('AB', models.PositiveIntegerField(default=0)),
                ('BB', models.PositiveIntegerField(default=0)),
                ('SO', models.PositiveIntegerField(default=0)),
                ('Singles', models.PositiveIntegerField(default=0)),
                ('Doubles', models.PositiveIntegerField(default=0)),
                ('Triples', models.PositiveIntegerField(default=0)),
                ('HR', models.PositiveIntegerField(default=0)),
                ('Runs', models.PositiveIntegerField(default=0)),
                ('RBI', models.PositiveIntegerField(default=0)),
                ('SB', models.PositiveIntegerField(default=0)),
                ('SAC', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='plays_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.team'),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='pitches_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='statalize_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='statalize_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.team'),
        ),
    ]
