# Generated by Django 5.1.2 on 2024-10-21 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
                ('player_age', models.PositiveIntegerField()),
                ('player_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('player_height', models.CharField(max_length=4)),
                ('player_weight', models.CharField(max_length=3)),
                ('plays_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(max_length=50)),
                ('coach_year', models.PositiveIntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statalize_app.team')),
            ],
        ),
    ]
